{{- if and (not .Values.observability.authorizationHeader.existingSecret) .Values.observability.authorizationHeader.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-collector.otelAuthorizationSecretName" . }}
  labels:
    {{- include "event-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.observability.authorizationHeader.existingSecretKey }}: {{ .Values.observability.authorizationHeader.value | quote }}
{{- end }}
