{{- if and (not .Values.webhookToken.existingSecret) .Values.webhookToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-collector.webhookSecretName" . }}
  labels:
    {{- include "event-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webhookToken.existingSecretKey }}: {{ .Values.webhookToken.value | quote }}
{{- end }}
